module.exports = [
    {"visited":true,"loading":false,"stars":2,"url":"http://christophjanz.blogspot.com/"},
    {"visited":true,"loading":false,"stars":2,"url":"http://tomtunguz.com/"},
    {"visited":true,"loading":false,"stars":2,"url":"http://blog.ycombinator.com/"},
    {"visited":false,"loading":false,"stars":2,"url":"https://saastr.quora.com/"},
    {"visited":false,"loading":false,"stars":2,"url":"http://a16z.com/"},
    {"visited":true,"loading":false,"stars":1,"url":"http://onstartups.com/"},
    {"visited":true,"loading":false,"stars":1,"url":"http://avc.com/"},
    {"visited":true,"loading":false,"stars":1,"url":"https://mattermark.com/blog/"},
    {"visited":true,"loading":false,"stars":0,"url":"http://digest.scottbelsky.com/"},{"visited":true,"loading":false,"stars":0,"url":"https://www.kennorton.com/essays/books-for-product-managers.html"},{"visited":true,"loading":false,"stars":0,"url":"http://blog.alchemistaccelerator.com/"},{"visited":true,"loading":false,"stars":0,"url":"https://insights.project-a.com/"},{"visited":true,"loading":false,"stars":0,"url":"http://dcvc.com/"},{"visited":true,"loading":false,"stars":0,"url":"http://andrewchen.co/recent/"},{"visited":false,"loading":false,"stars":0,"url":"https://medium.com/high-alpha"},{"visited":true,"loading":false,"stars":0,"url":"http://www.thetwentyminutevc.com/"},{"visited":true,"loading":false,"stars":0,"url":"https://siftery.com/stories"},{"visited":true,"loading":false,"stars":0,"url":"https://blog.angel.co/"},{"visited":false,"loading":false,"stars":0,"url":"https://overcast.fm/itunes1215439780/equity"},{"visited":true,"loading":false,"stars":0,"url":"http://blog.samaltman.com/"},{"visited":true,"loading":false,"stars":0,"url":"https://techcrunch.com/"},{"visited":true,"loading":false,"stars":0,"url":"https://www.theinformation.com/"},{"visited":true,"loading":false,"stars":0,"url":"http://www.feld.com/"},{"visited":true,"loading":false,"stars":0,"url":"https://nextgenvp.com/portfolio/"},{"visited":true,"loading":false,"stars":0,"url":"https://www.indiehackers.com/businesses"},{"visited":true,"loading":false,"stars":0,"url":"http://blog.bridgegroupinc.com/"},{"visited":false,"loading":false,"stars":0,"url":"http://www.forentrepreneurs.com/"}
];
